services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=ExpenseTrackerDB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ExpenseTrackerDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: postgresDB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=ExpenseTrackerDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres: