services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - spring-postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: postgresDB
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    env_file:
      - .env
    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres: